// <auto-generated />
using Diary.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Diary.Migrations
{
    [DbContext(typeof(DiaryContext))]
    [Migration("20210609112753_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Diary.Models.DiaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Entry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = 2,
                            Entry = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu scelerisque turpis. Aliquam consectetur pharetra mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tincidunt et nisi sit amet rutrum. Nunc consequat, leo a mattis condimentum, orci mi consequat lacus, eu pulvinar tortor ante eu leo. Proin blandit mi eu nulla scelerisque gravida. Donec id sem nec velit congue ullamcorper a quis augue. Nunc posuere facilisis efficitur. Sed id lectus luctus, lobortis lectus vitae, eleifend lorem. Aliquam nulla est, vestibulum sit amet risus nec, iaculis molestie mauris. Vivamus congue augue ligula, quis blandit leocommodo vitae. Aliquam ornare quam at faucibus pharetra. Etiam condimentum a arcu et pretium. Pellentesque non mauris quis ipsum finibus faucibus.",
                            Title = "Wpis 1"
                        },
                        new
                        {
                            Id = 2,
                            Day = 2,
                            Entry = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu scelerisque turpis. Aliquam consectetur pharetra mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tincidunt et nisi sit amet rutrum. Nunc consequat, leo a mattis condimentum, orci mi consequat lacus, eu pulvinar tortor ante eu leo. Proin blandit mi eu nulla scelerisque gravida. Donec id sem nec velit congue ullamcorper a quis augue. Nunc posuere facilisis efficitur. Sed id lectus luctus, lobortis lectus vitae, eleifend lorem. Aliquam nulla est, vestibulum sit amet risus nec, iaculis molestie mauris. Vivamus congue augue ligula, quis blandit leocommodo vitae. Aliquam ornare quam at faucibus pharetra. Etiam condimentum a arcu et pretium. Pellentesque non mauris quis ipsum finibus faucibus.",
                            Title = "Wpis 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
